### ISSUE TITLE
Event callbacks execute in the thread of where the event is fired

### ISSUE THREAD

**Issue by geiseri** [ptsouchlos/eventbus#25] opened 2021-04-26 00:39 UTC
The callback from the listener will execute in the emitters thread. This will cause all sorts of "interesting" issues with cross-thread use.  For this to be usable in a multi-thread environment you need to ensure that the listener's callback executes in the thread it was allocated in and not the thread the emitter runs in.  It will also need to run in a "detached" state as to not block the emitter's thread while the event is being processed.

**Comment by ptsouchlos** [comment] 2021-04-26 16:31
Do you happen to have a minimum reproducible example handy?

**Comment by geiseri** [comment] 2021-04-26 18:32
I modified demo.cpp accordingly:
[demo.zip](https://github.com/DeveloperPaul123/eventbus/files/6379308/demo.zip)

This outputs the following:

```
I just do stuff when a third_event is fired. 140065430034240
my third event handler: 13 140065430034240
I just do stuff when a third_event is fired. 140065430034240
thread function140065430030080
third event handler says: oh boy... 140065430030080
event: oh boy... 140065430030080
Firing other event
second other event handler says: 2 hello there 140065430030080
first other event handler says: hello there 140065430030080
Firing other event
second other event handler says: 2 hello there 140065430030080
first other event handler says: hello there 140065430030080
I just do stuff when a third_event is fired. 140065430030080
callback count: 1
handler count: 7
removing handlers...
```

You will notice that the main thread has an ID of `140065430034240`.  This is where the event listeners are hooked up.  Then you will see when the thread is spawned it has an ID of `140065430030080`.  From that point on all listener, callbacks run in that thread context.

**Comment by ptsouchlos** [comment] 2021-04-28 19:50
> From that point on all listener, callbacks run in that thread context.

You mean when events are fired from within that thread context right? The way I understand the issue is that the context of the callback changes depending on where the event is fired.

If you have any suggestions on how you would approach handling this I'm all ears. I've looked into it and it seems the common ways to handle this would introduce quite a bit of overhead to the library which I would like to avoid.

**Comment by geiseri** [comment] 2021-04-29 01:33
Yes, you need to serialize the event on the subscriber's thread, but as with all things concurrent, you pay the price :(.  In Qt, they have a per-thread event loop for signals and slots, and in rxcpp they use a task and scheduler approach.  I think the fundamental flaw in your scheme is that the publisher invokes the action, where normally in an event bus the subscriber will take the event from the queue.  These are hard issues to solve without an event loop/scheduler, and sadly I do not have good answers. (hence why I have been hunting for an existing project ;) )

In the meantime, I would try to make it very clear that this should NOT be used under any circumstance where a thread could emit an event that another thread would receive.  Even if you were okay with that risk, thread pools are completely off the table.

This library would be a good alternative to the signals/slots approach when you don't want to deal with abstraction layers to forward signals.

**Comment by ptsouchlos** [comment] 2021-04-29 13:39
Ok I see. This was the conclusion that I came to and honestly, implementing something like that may be beyond the scope of this library for now. 

I will at a minimum update the readme to make this clear. Thanks for finding this and sharing.

**Comment by ptsouchlos** [comment] 2021-04-30 15:17
After looking through it more I've come to the conclusion that addressing this behavior is beyond the scope of what this library is trying to accomplish. There would be a lot of overhead to get it working properly so for now this will remain a `wontfix` issue.

**Closed as completed by ptsouchlos** 2021-04-30 15:17 UTC
Labels: wontfix
